// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqJjDRLdwb0Y83XYj78Ck3GzFOowjrOsw',
    appId: '1:374992688661:web:e8af6ef9e9c39dc89a201c',
    messagingSenderId: '374992688661',
    projectId: 'waterreminder-8c84b',
    authDomain: 'waterreminder-8c84b.firebaseapp.com',
    databaseURL: 'https://waterreminder-8c84b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'waterreminder-8c84b.appspot.com',
    measurementId: 'G-VR3Q36HKDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXuEuR6dxwpF2gvQ0S_2WDjqlQlMlLFIo',
    appId: '1:374992688661:android:5e4146b81be8d6669a201c',
    messagingSenderId: '374992688661',
    projectId: 'waterreminder-8c84b',
    databaseURL: 'https://waterreminder-8c84b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'waterreminder-8c84b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnnMEdiLwb43k_qhtgOC7FpXB2DMOnvmA',
    appId: '1:374992688661:ios:4b92abe18783b1da9a201c',
    messagingSenderId: '374992688661',
    projectId: 'waterreminder-8c84b',
    databaseURL: 'https://waterreminder-8c84b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'waterreminder-8c84b.appspot.com',
    iosBundleId: 'com.example.waterReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnnMEdiLwb43k_qhtgOC7FpXB2DMOnvmA',
    appId: '1:374992688661:ios:cfe828925d1217489a201c',
    messagingSenderId: '374992688661',
    projectId: 'waterreminder-8c84b',
    databaseURL: 'https://waterreminder-8c84b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'waterreminder-8c84b.appspot.com',
    iosBundleId: 'com.example.waterReminder.RunnerTests',
  );
}
